ktor:
  application:
    modules:
      - com.maran.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "url"
  user: user
  password: password

jwt:
  secret: secret
  issuer: "http://0.0.0.0:8080/"
  realm: "access"